### ISSUE TITLE
Runtime error with Python-3.13

### ISSUE THREAD

**Issue by vext01** [DRMacIver/shrinkray#14]
Hi David,

Neat project. Thanks for this.

Annoyingly Debian's Python is too old to run a new shrinkray, so I built a Python-3.13.1 from source tarball and installed shrinkray from git using `pip`. The install worked fine, but I got the following runtime exception:

```
$ /opt/python3/bin/shrinkray --timeout -1 reduce.sh bork.lua                                              (git:more-tests)
Traceback (most recent call last):
  File "/opt/python3/bin/shrinkray", line 5, in <module>
    from shrinkray.__main__ import main
  File "/opt/python3/lib/python3.13/site-packages/shrinkray/__main__.py", line 22, in <module>
    import trio
  File "/opt/python3/lib/python3.13/site-packages/trio/__init__.py", line 71, in <module>
    from ._path import Path as Path
  File "/opt/python3/lib/python3.13/site-packages/trio/_path.py", line 134, in <module>
    class Path(metaclass=AsyncAutoWrapperType):
    ...<125 lines>...
                with_segments: Any
  File "/opt/python3/lib/python3.13/site-packages/trio/_path.py", line 85, in __init__
    type(cls).generate_forwards(cls, attrs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/opt/python3/lib/python3.13/site-packages/trio/_path.py", line 102, in generate_forwards
    raise TypeError(attr_name, type(attr))
TypeError: ('parser', <class 'module'>)
```

I assume this to work since the docs say:

> Shrink Ray requires Python 3.12 or later

I repeated the same steps, but with Python 3.12.8 and it worked fine.

Cheers.

**Comment by seanm** [comment]
I got past bug #15 but then I hit this too.

Oh well, back to creduce I guess.

**Comment by DRMacIver** [comment]
Thanks for the report! The version of trio shrinkray was using was one from before 3.13.0 came out and it needed updating. I've updated the dependency and this should work now, but I've not tested it extensively yet.
