### ISSUE TITLE
urwid Unicode Errors when Minimising Binary Data

### ISSUE THREAD

**Issue by frankplow** [DRMacIver/shrinkray#9]
Hi, thanks a lot for shrinkray!  I have been using it to minimise some binary formats and generally been finding it very effective, however occasionally I run into errors along the lines of:
```
/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/text_layout.py:262: UnicodeWarning: `calc_width` with text encoded to bytes can produce incorrect resultsdue to possible offset in the middle of character: 'utf-8' codec can't decode byte 0xcd in position 0: invalid continuation byteb811e16cb4c10d906bd57ec0b0c8302c14ea2475041728faceb0048f24a27272223b0719279749
  screen_columns = calc_width(text, idx, nl_pos)30bc471fc4a53f6edd4807cf16f6a4420b0b00e98e89470f37c7eff3fd4507d42d2186db4538e0d133201c64084f7511a1952857e97b76d2ed93e9b38ce0f6f7668f5c77bff641c82b773a992828f1dc3cdf598c6d7eb6561ae92560dedd8156ec45d78b306a9032b031a40eda4bebde8d32fc5f52ea
/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/text_layout.py:262: UnicodeWarning: `calc_width` with text encoded to bytes can produce incorrect resultsdue to possible offset in the middle of character: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte6ad2f676b707633535e28
  screen_columns = calc_width(text, idx, nl_pos)22c87f747cd06eca1a8cc3ae8551ec3711b8fe9f268d4116f9238a7d302e613797ba070e54b079ab44076ae3cb193fffc2dd027500932db725c87cb2af713f347be6fe3e050f0cf7e8b1ef07b8671ebcc9413c5a3953987ee3a6c4eb401859cf30199cf963bda07e795ecd71c2ce9a353a1fb88523b8
/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/text_layout.py:262: UnicodeWarning: `calc_width` with text encoded to bytes can produce incorrect resultsdue to possible offset in the middle of character: 'utf-8' codec can't decode byte 0x8a in position 0: invalid start bytebb33f44d3b22074bd270ff9c033faa4668fef11ad2ba79f901bb05e35ba4a35cdd50052f7d59e1b9025b5e575de05756f40e6f6f9f7fbc9d9523f5051c1806fd7ee826e44dfcd617afb63ca896b86e4aaed98006f4ea5e15ecb80aae65e8045b6687d7df6406148621c
  screen_columns = calc_width(text, idx, nl_pos)64ad6ff1cf598fec8e639fc264d54472c
/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/text_layout.py:262: UnicodeWarning: `calc_width` with text encoded to bytes can produce incorrect resultsdue to possible offset in the middle of character: 'utf-8' codec can't decode byte 0xc8 in position 0: invalid continuation byte00000100411578c5c911a3bd73cc252f31c7939259e5c95ef9e27111558685583f22a921b21d5e8f8257be81530ffd3da922f77172a577413f9d91b6519a860fd8109cfd1bc4ecedae250c649ebd0f62f44890f1f867e6b2ea68131e4f402b3cb7365be4fd698b6437fde72c2dff6cc2a4d14c146263e69269092e9f0401b009584a7eb68f3
  screen_columns = calc_width(text, idx, nl_pos)fb0502b65fc3394355a9ec0e59de7d15741789db1ca1518fbae340d3cb5b672e1d186e120c5175d95f311f8a599054fc0c17acaf2f8735aad00466f592de78eeba615acf32d794a4139cc772afc8be00633194f9b8508bdf430872d4625a6e51782346380395a8535777070e85e9692ca6f044f3578a
/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/text_layout.py:262: UnicodeWarning: `calc_width` with text encoded to bytes can produce incorrect resultsdue to possible offset in the middle of character: 'utf-8' codec can't decode byte 0xae in position 0: invalid start byteb8a8e15320fef1fa2633157395636282761c9db9f9652af0eedad43021901c418b481a6345cd444d918e4811f2d163d797ce404ac092b3e
  screen_columns = calc_width(text, idx, nl_pos)90bca1865ee68a0482f14b714bfa7076d3c26837e56bed3be2a8ce5194aef96b348a66699da261432e53f0567fcb1f724601275e5c7e00867f0d016e313a5bfbd348f12e9033a8b4b80417fbcdcc096fa046fcc7fcfae2cfb2181c0908fc07c90858948199125b96f1033b18cd8ca9d5655b79ae31d9
/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/text_layout.py:262: UnicodeWarning: `calc_width` with text encoded to bytes can produce incorrect resultsdue to possible offset in the middle of character: 'utf-8' codec can't decode byte 0xf8 in position 1: invalid start bytebc616c03278396f3b31e293297a
  screen_columns = calc_width(text, idx, nl_pos)eaa0d73a179e0531ef1baa71d680ee344cb3ce0c4b7a637bf4f0fcbb6
Exception raised when calling 'before_io_wait' on instrument <urwid.event_loop.trio_loop._TrioIdleCallbackInstrument object at 0x102f35270>. Instrument has been disabled.
Traceback (most recent call last):92cc36446ba6d67bad0696d55d56185bbc40015b426487b396eb3b716a1db1087dc75715e698d6de6a32f9e5f77d5a07ff87370be8c037b6d664f2c68858224aaeeae3275a7901288a9a577430bc943f8a7c08a742ddd044087824084d95266b9283c1be002c5739f690b0b448a8a269c151707b57ef05045eb87e1043
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/trio/_core/_instrumentation.py", line 100, in calle7488772892f69e2eba58cef9784064493c27981e925446d675e20b7f33e40dc6285c8965dd72df079a5eaffe8357eee0efbbe203d6abb55badeea70315063a8585606d11bc96d2cade440489b75a53e7196
    getattr(instrument, hookname)(*args)72db350714c7aa06814a3f664644f0fa5f6f853d06ec80795f36fa31d19e283e15f6fd1dbe261a0800000010001350bf0e20d515bc22cdd1c16bd9458040191a828b187d8671ae12c8fa6e92fd01cf7ffffffded053cb0e5652a9f32bb61f34d887cf024f57754dfc41039de08833d7e1d3d93cbec4efc8e53a3
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/event_loop/trio_loop.py", line 61, in before_io_waitbca7e9a52457002ac1c5a8dbeff60c2371e8b699d98cc418425abc7759368891597741636b51dc6d385106a824d119fd6b7
    idle_callback()dbdf32012e5df88d6b7b987027981f6e45ac06b6712118777777e37612a52f6bfe7f9232
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/event_loop/main_loop.py", line 650, in entering_idle
    self.draw_screen()99fa94c91e92278ed456fed62b0e4f0fc06d7059552a3ef6a410531d3525afd5630e78089a3322a941ad53c205c5d80476515c2666adfdb6c16364b7056bef1ca877c2bb55d8a015c7e65e0cbf7454db076c55ade44d2e72aa08310bbcb7a08509610c30e08c6e2368677438625c5b155de5e84cf0c47a553a25a5b0e4d6bf6992dec3
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/event_loop/main_loop.py", line 667, in draw_screenf
    canvas = self._topmost_widget.render(self.screen_size, focus=True)1bec07547199ff1d5b7ab1ba604ce29bf827e62ec314b5178f4a76e8660a7d47a771b4335195a47a57b5cbf45801e1abe6f533673bc434fb7d002d37517593bd9c463021467389f4be4348b924a9f6ab3662b409ebead0e2f3a45e1946d6eb30b3efac046dc18698f1110c
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^a0c53291058639e84bde16dd9e7e6d84f8e4a0465ccb4096dffab1722d7eb387e11b0954f739f7dcc67870c45d039827d563a754a5f40bb0598d59edb62e6c67b3a05463588d17b031a460f723e21cbd3477b9a29a80caa608c7f9d5265b9082d17570b4dc441398bc52ff
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/widget/widget.py", line 112, in cached_render918aa9b62ef7425cfe817d26c7d1a58caa5c032c2edd2fe2f6c94032f930a310af91ac430769ab74760eb5884b93819b0fddb07ac7cc00b282480cb74d43488bae2e3cf33411af01b5249b2d102100974f3
    canv = fn(self, size, focus=focus)5f806864f7fde462481db26420358317c0538ff5d6602b07ab6cee330a6f9c0100eb3600d52dc5048e04d4099581b71889fcb08b09f1dddffd6122625ad9c964855c8aee27d9c66cb0b3845380871325adbc43ad4cfc141c2aec9e30ce708323142c35c540ea1e0ef3d9ee9d8daca99d2f115dd5629173c8a2ecf1
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^9ccb49c96080250b6e2f2c6d0a1e3fa6317a21f8f5cf3ca3fb5eb6d0d5d3d279e1174ce6797e67ac15c5f995cdd039ed7eb0427971c89f52f5da7812bd1656cca892260c9e94e01c5828dc3b6b506ce7fac539a03adb6897705619bbdeaac45284c96737aeaa29b4c03cf95e406a3471d3f5792b74a2e1ac0fed27
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/widget/frame.py", line 481, in rendere14f31c3d087886bbd658103dfc10b155e206cfa34afceca70ef0ec530574583e91df644f908025443517fb63e7f0b044266be6867f3c85d0131cbc32b98ebc541f233a1ebc83eac3284f6b25375a6bb9e7ac6a95e5
    body = self.body.render((maxcol, maxrow - ftrim - htrim), focus and self.focus_part == "body")62929d98a6a22861502417b6f31da85e48a7b62e63b513c6978cbba181c9c00c1f214814af689eaa6ac0d9a2ca0242ccb651ccc50687831bac92b5fa77bc55dd9e4f9f6068c1f979c295bdba8c1d23ec2fa8e9a2499081ae9a6cb8a78d
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/widget/widget.py", line 112, in cached_renderc79f4f0e672fe8b8515b5d0131cbc32b98ebc541f233a1ebc83eac3284f6b25375a6bb9e7ac6a95e5c5d24ccfe465dcab4feb28cd6fd79307c0fc00000010041346f80f914f6a36f5eaf75fc94522fece9d
    canv = fn(self, size, focus=focus)b6f31da85e48a7b62e63b513c6978cbba181c9c00c1f214814af689eaa6ac0d9a2ca0242ccb651ccc50687831bac92b5fa77bc55dd9e4f9f6068c1f979c295bdba8c1d23ec2fa8e9a2499081ae9a6cb8a78d3755a68a7cb0ca3a978b77d4233ffa21ac1c8e04b68a774bae9ef62bc29faa5595f675b00
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^2c377aa938994d1861c5cc41aa95d47e22d42ed66172d799449aca3defde93b9290e28d7c162e2e32d56be8e1317f435822496c3bf3f0643d8ad55226fe7e01958319ca
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/widget/attr_map.py", line 158, in render2ecf1876b93417854075a02bf214e367432cc9d6cc73e01ea02281c6f861db73afb2660fd9d2eafaaccc23943c67665c67c9ce28b831bbf034ab163b1b9716241
    canv = self._original_widget.render(size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^aca88344c80c009d209a2249f90dcde1f68067a15580cb08edc6fb4a7bc1a80e81401bb75622de3c03d977135007badfc88b3c5759db2bfb332d44b1b3ac7db29cd3793c85c85ba5e808f2aadc96b6d06d50cbaa144bbaf8f63da6a728e360ed7f060f5d9d7a27784999aa0c972c73fc8c
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/widget/widget.py", line 112, in cached_render7cddba598e9a31039a5be542171b5c74b741178ce5820729d167c0df596cac83377c18da9af8e8e5933cead392998b72dd93053a1ca178116ad90e3294e42faecbb1b221955c17ec221d8cf4b4741a9fe7a
    canv = fn(self, size, focus=focus)61b2c5c6850752557f9fec99405f4125e966b7cfc8132b58600708f3a732e65686a47c3fe2c59cdde657d4d50d418146a0d75ea7881de00a9d001316adc59759d1fa1b81aa1a7019641934db2cbdc6bde1dea730ba2ae37ce21330866691bc99a9aa0d15cb4dc7f3eb56cbfd03e3773f1b51670875285d1e93db79
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^6d726a85fc01ef31c5c1bdb3c3e4e5fa5708d430996fb3e7e20afcd6a697fdf1481c15bb19b2069f3b9ddc93a8998
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/widget/listbox.py", line 712, in rendere8184c6aebddcde14a28d253b044b72ab9ca6227bd7b02d0e3fa7fb56f67657dc3babe6a04c8e44b7cb48a8b6b69002a381269bb2250aa0de315d3bc6aeb92002004998b243733bb4c30c416010c73ea6eeb7ff36
    middle, top, bottom = self.calculate_visible((maxcol, maxrow), focus=focus)b44aaf48af19b33537af356b60b55d3acb41cbada03ebae66135c0045806bd28817e128b90ed02bfd4be83b960b418ff47ad535f848af9851ade20384a4ea0f8d20ca017b777417647f48770549803e4e355ed1b0f656af06dad1d8d20e7c311de115e28c1833
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^a71f0c147747ba2f75398b634a19293f432eb7327f3aa62dfe63982dd572b5ec2709d338e3fff5d63aecfecfe686e8becf050625a5f8167014f65a605f9c8feaad323f00b433d2d7e5246d035bfe9a4e191ec19b022ecee6745904b496e1c35b39afa38e
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/widget/listbox.py", line 551, in calculate_visible0938010be721aef823fa3634673d30d49e9dc32d91178082ac262c61dd1caabfc678e323de2f47cb23a8b766f0f104b13914896d5a2860dcc142cf8a075e4408c6b5af7595962a8af3961f9dd98827
    n_rows = next_pos.rows((maxcol,))9d80a29c1b11362f53946cbf7bec2c6759af43b1c567a5ffab50a8cc2d0b438532631e09b68bb11ac45f169e7843d47ca8950958fbd0d11990b9f446c7c2a35a36e7256e36ef9a8636ae98d0f3718b2e8ed81e4ed7528ec758afe86b1520c7305d4aef8638d7d27ffb03137a290680338207315498e6c527ff58150
             ^^^^^^^^^^^^^^^^^^^^^^^^ca57dccd4b5ecb70204e8e57af6f6e8bc46db096db9ffd3d6b6f753abfe049785493eebbcd0453259171b51b5df7143a911c97181ca5d4d0f2f99245a713ef3f3ae64217c28189ae9de61bd6e4017d8f0f57973ec2a118040c1b12c4da6806d9f8f6471a87952aa9724063c9d1ad0e142c28500e149b98a25389432
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/widget/widget.py", line 181, in cached_rows002a7543ff7bc91caa3422c5d526c4b36df6ae96fc9f2408b9699c9e9b263bda820f1b602d2d722866fb45f333a1158489999144d7c6af73f23c9d
    return fn(self, size, focus)48b73e2f71b3fc9cc860474f343d7dd33a0f997629e59b468a00d6ab10ff8bf7e55d9a49242fc5a554c07c7da933549ccda3f7d60cd931fa8f8
           ^^^^^^^^^^^^^^^^^^^^^e094a5118f1404111519b4b3d6df9762214194bae1c5f4928e17bd44ae1ec7380b64c6fdfb354019fbeb26a5a58a9db7f1077fc82a3bd8145058bdcc0ec34f0b79e5f836f47979a2c6d97712d8a205560b18341ed1b7b
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/widget/text.py", line 286, in rowsd7a67924df172e6838d2b606dda75a28636ce69b9a3153550d3446310f0a9d42fb54dd2bb163754d63226176c07b03df97b16a8c8b93787224195bcb3d0714a50a47ad320f22c4ce62c8d0b7b1ccb2ae238edc35f60304
    return len(self.get_line_translation(maxcol))dc815b5389eeaaede61e96f330c39a3ef03c7029b8c82154d9b20b32a3822690a0e96cfe531e3af4777c41393c69db7716a725388b98a400e9f4eab908d65ba5f447ee017f1f099924a01ee67dcdf391c5
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^c85453d00a3091e72cf08be50ef050d38
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/widget/text.py", line 304, in get_line_translation
    self._update_cache_translation(maxcol, ta)47f29ca28478b467798f2347f41001e7f7efdad35e857f5917d7e3e00b906ea30f0108107ef0974125d6a17be03db66ccf46384cc72ba3e839cbd1ef532c234348b5f552900d608d989e38bf1931cc49227756af1902c8bd0ca4ba87e2fedeb9acb4eb175d1509aa7071feb1f22ea45ae97b8fe899eb29
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/widget/text.py", line 317, in _update_cache_translation
    self._cache_translation = self.layout.layout(text, maxcol, self._align_mode, self._wrap_mode)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^d0b48badd7fddf88c6903089dcc187243c47441ae79c00e485aea2910714b0533cd91961fe826a06e853cdbf928d21f5092bef4beb344ea69d0b72d26f339788cac553f41b1855ebbf36652981536aa5902bcf9ec1d08aa250faa2bb9f4
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/text_layout.py", line 126, in layout
    segs = self.calculate_text_segments(text, width, wrap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^03b68eab4b80668e12452d62933ab87a1b03e17bdf19b5e59e4d92d26c28fc598da18a6e23969abc5ad00f18a8eb34a888161bdb14e29cc08fc2484875c255a710d220fdd16a77f70f9703d6a20c17848852ff88201adc4fafd7dfce757c8986afd6e02a45e501259f2c6c87fb3e6849c5
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/text_layout.py", line 262, in calculate_text_segments57f9f531695cea84f23dad3fc2da3b9589d9650b31d65487e48140453237016a1d3e93eca87e5881525b9f15715e2e75fd02fd05f6056695bd344e89b64fb1277a8270d2c26198473ddb493ee90
    screen_columns = calc_width(text, idx, nl_pos)5cac66eabca6a92969904a970781828a118debda24521e32f91dba1e2bb8950d472839ba8674d147eb5421f561f97fd3afcd304d452474456974da3efd22d37fc6b79feb9f022e6eb5cadb6da24cff1605affbf542281c454fa3d6ab94f568bd036a118d8544f21506df0cf088b6ac9202aef0648f
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^db9ede3ae25c64989896aca0e628765b435bf82b79a288e73ca2d2fe8
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/str_util.py", line 256, in calc_width
    w = get_width(o)
        ^^^^^^^^^^^^
  File "/Users/frank/Dev/shrinkray/.venv/lib/python3.12/site-packages/urwid/str_util.py", line 47, in get_width
    return get_char_width(chr(o))
                          ^^^^^^
ValueError: chr() arg not in range(0x110000)
  ```
  when using the urwid UI, even with `--formatter none`.
  
shrinkray seems to be able to handle some of these to a certain extent: sometimes I see a Python stacktrace appear and corrupt the stdout, however minimisation persists.  The particular error from the trace above however always coincides with the program halting.

If you want to reproduce this, try seed 0 with this file: [000311.bit.tar.gz](https://github.com/user-attachments/files/17451024/000311.bit.tar.gz) and this interestingness test (requires `--input-type arg`):
```bash
#!/usr/bin/env bash

FFMPEG_PATH="$HOME/dev/shrinkray/ffmpeg_g"

"$FFMPEG_PATH" -i "$1" -fps_mode passthrough -noautoscale -f null -

exitcode=$?
echo "FFmpeg exited with code $exitcode"
test "$exitcode" -eq 134
```
with FFmpeg revision b61141056939acfd67e51dbd05c2c8c729d6b31b compiled with Address Sanitizer.  Sorry this is so involved!  I did try to come up with a more minimal repro but the issue only seems to occur infrequently on sizable inputs.

**Comment by frankplow** [comment]
If I comment out the call to set the display text:
```diff
diff --git a/src/shrinkray/__main__.py b/src/shrinkray/__main__.py
index 197f50d..77f4fb6 100644
--- a/src/shrinkray/__main__.py
+++ b/src/shrinkray/__main__.py
@@ -889,7 +889,7 @@ class ShrinkRayUISingleFile(UrwidUI[bytes]):
             ):
                 await trio.sleep(0.5)
                 continue
-            self.diff_to_display.set_text(diff)
+            # self.diff_to_display.set_text(diff)
             prev = current
             prev_unformatted = self.problem.current_test_case
             time_of_last_update = time.time()
```
then I don't get any of the hex diff output in the main window, however the issue persists, which surprises me.
